sudo: false
language: python
python:
  - '3.5'
  
install:
  - pip install -U tox
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://mark.stridespace.com

env:
  global:
    - RESULTS=results.xml{testing}
  matrix:
#     - TESTENV=coveralls 
#     - TESTENV=linting 
     - TESTENV=py26 
     - TESTENV=py27 
     - TESTENV=py33 
     - TESTENV=py34 
     - TESTENV=py35 
     - TESTENV=pypy 
     - TESTENV=py27-pexpect 
     - TESTENV=py27-xdist 
     - TESTENV=py27-trial 
     - TESTENV=py35-pexpect 
     - TESTENV=py35-xdist 
     - TESTENV=py35-trial 
     - TESTENV=py27-nobyte 
#     - TESTENV=doctesting 
#     - TESTENV=freeze
#     - TESTENV=docs 

matrix:
  include:
    - env: TESTENV=py36 
      python: 3.6-dev
    - env: TESTENV=py37
      python: nightly

script:
  - tox --recreate -e $TESTENV

after_script:
  - testspace [$TESTENV]$RESULTS 
